name: Code Quality Checks
on:
  push:
    branches: ['*']
jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.65.0
          override: true
          profile: minimal
      - name: Run cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
  check:
    name: Cargo Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.65.0
          override: true
          profile: minimal
      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: check
  clippy:
    name: Cargo Clippy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.65.0
          override: true
          profile: minimal
          components: clippy
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: -- -D warnings
  fmt:
    name: Cargo Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.65.0
          override: true
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check
